### ISSUE TITLE
console.log occurring every second during recording

### ISSUE THREAD

**Issue by marknorrapscm** [sivaprakashDesingu/react-voice-recorder#16]
Bit confused by this one as line 155 in Recorder.js is commented out but I'm still getting the svg console.logged every second during a recording:

![image](https://user-images.githubusercontent.com/34408415/114319717-8c414c80-9b0a-11eb-91aa-a31841ce045c.png)

Not a major issue but it would be good to remove.

**Comment by sivaprakashDesingu** [comment]
Thanks for the Issue and PR raised. You PR has been approved and merged with master branch.

**Comment by marknorrapscm** [comment]
@sivaprakashDesingu Good job! Could you please increment the version number? Right now it's still on v2.0.7. A bump to 2.0.8 and a re-publish to NPM would be great.
