### ISSUE TITLE
Forked repo

### ISSUE THREAD

**Issue by Cchumi** [sivaprakashDesingu/react-voice-recorder#2]
Hi I love your module but I need to expand functionality like css and another control on the recorder to toggle or not the recorder. 

So I fork your repo install in my node react app but I am not able to use your module forked. 
When I install your version in my node module it comes compiled but when I install my version It comes not compiled so I try running npm build but got an error. 

Please can you give me advice to compile it ?

Thanks

**Comment by sivaprakashDesingu** [comment]
Thanks for the support.

Please let me know the "Error" that you are getting while build so that i can identify and help you out reg the same

**Comment by Cchumi** [comment]
Hi and thanks for your answer. 
It’s a webpack error 

webpack module parse failed: unexpected token

It’s about a missing part. 
And can I use un compiled version of your repo ?

**Comment by sivaprakashDesingu** [comment]
I hope you had run => npm install before build...

It is working in my system with npm. Have facing the same issue npm too please?

**Comment by Cchumi** [comment]
I already run npm before all of this. 
Which version of npm did you have ?

**Comment by sivaprakashDesingu** [comment]
Mine is 5.6.0 also working on higher version 6+...

If you have skype,  please ping me on skype. Skype id is **shivasing14**

**Comment by sivaprakashDesingu** [comment]
@Cchumi  I have completely modified this library package, You can try it out now.

Now I am closing this issue, if you face the same issue please let me know.
