### ISSUE TITLE
Error In devices with no microphone

### ISSUE THREAD

**Issue by ahmadkam72** [sivaprakashDesingu/react-voice-recorder#20]
In devices that do not have microphone, clicking on voice recorder show error.
Is there any way to avoid this error?
Thank you.

**Comment by sivaprakashDesingu** [comment]
Could you please share the snapshot of the issue that you are getting?

**Comment by ahmadkam72** [comment]
The error what I faced is 
Can not read property 'start' of undefined
![Screenshot from 2021-06-10 01-48-41](https://user-images.githubusercontent.com/46483166/121431086-3106cb80-c98e-11eb-87db-fcfbb9ee3a43.png)

**Comment by sivaprakashDesingu** [comment]
May i know the version of browser that your the getting this issue.

Make sure is you are running this on Either localhost or SSL server. In case if you are getting this issue on NonSSL server you will get this issue. From outside we should make this show be handled that should not break the applicaiton and let show some alret.
