### ISSUE TITLE
mimeTypeToUseWhenRecording - what types?

### ISSUE THREAD

**Issue by bvelasquez** [sivaprakashDesingu/react-voice-recorder#21]
Hello,

Does this record only in the default audio type for the browser, or can it support more audio types? I would like to record on the desktop web app, and play it back on iOS or Android devices.

Thank you,

Barry

**Comment by sivaprakashDesingu** [comment]
@bvelasquez 
Currently we have only mimeTypeToUseWhenRecording={`audio/webm`} .

Thanks,
Shiva.
