### ISSUE TITLE
How to customize

### ISSUE THREAD

**Issue by JohnGoodman** [sivaprakashDesingu/react-voice-recorder#22]
Hey, thanks for creating this package. I'm trying to customize the package to use my own UI. To do this, I need a way to call the `startRecording` and `stopRecording` methods from my own buttons. Can you provide any insight on how to do this?

**Comment by sivaprakashDesingu** [comment]
@JohnGoodman  Thanks for using this package. Currently, we don't have customized option for the same. will be working in future release.
