### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by Rishabh6211** [sivaprakashDesingu/react-voice-recorder#26]
<Recorder
record={true}
title={"New recording"}
audioURL={audioDetails.url}
showUIAudio ={true}
hideHeader={true}
// handleOnChange={(value) => handleOnChange(value, 'firstname')}
handleAudioStop={data => handleAudioStop(data)}
mimeTypeToUseWhenRecording={`audio/webm`}

 />

**Comment by sivaprakashDesingu** [comment]
@Rishabh6211  Sorry for the delay. Can you provide the screenshot of the error that you are facing plz. so that we can help you out to fix that.

**Comment by eliranmoyal** [comment]
@Rishabh6211 maybe you didn't approve the popup to allow recording?

**Comment by sivaprakashDesingu** [comment]
@Rishabh6211  yeah.. You should allow while pop up.. else you will not be able to record.
