### ISSUE TITLE
Red Dot in favicon persist even after recording stopped

### ISSUE THREAD

**Issue by rohitmyaim** [sivaprakashDesingu/react-voice-recorder#27]
The stopRecording function has to properly handle stop track recording as given in below url

https://pretagteam.com/question/remove-red-icon-after-recording-has-stopped

![image](https://user-images.githubusercontent.com/5087134/140654300-d96321cd-d0df-4ec8-a578-30594938c50e.png)

**Comment by rohitmyaim** [comment]
![image](https://user-images.githubusercontent.com/5087134/140654449-0cf5feab-f2e9-403a-9ee7-e4ea354f77ab.png)

I tried creating a PR but Access denied to push so please fix this.

Thanks for creating such a good module

**Comment by OzdemirEmrah** [comment]
MediaRecorder can't access to getAudioTracks method. It should be MediaStream. I have created pull request to fixes.  [pull-33](https://github.com/sivaprakashDesingu/react-voice-recorder/pull/33)

**Comment by sivaprakashDesingu** [comment]
@OzdemirEmrah   Thanks for the PR, Will check your PR and merge your code.

**Comment by sivaprakashDesingu** [comment]
@OzdemirEmrah  After merged your code getting the below issue. Please fix and Create PR again
![download](https://user-images.githubusercontent.com/10977339/142007795-fb5dff73-6610-4fb4-a890-e2073a293b2f.png)
n.

**Comment by OzdemirEmrah** [comment]
> @OzdemirEmrah After merged your code getting the below issue. Please fix and Create PR again, For now, we are about to revert your change. Once you fixed that issue, will merge the code again. Also has some documentation on README file. ![download](https://user-images.githubusercontent.com/10977339/142007795-fb5dff73-6610-4fb4-a890-e2073a293b2f.png) n.

it's new feature, you must pass handleCountDown parameter to compontent.
for example;
`<Recorder ...otherprops handleCountDown={(d)=> console.log(d)}>`

**Comment by sivaprakashDesingu** [comment]
@OzdemirEmrah  Update the documentation with the brief into, So use will come to know the purpose of new feature.
We should give to the user with clear guideline when they come here and go through.

**Comment by OzdemirEmrah** [comment]
@sivaprakashDesingu Readme updated and handleCountDown added to default props. [pull-34](https://github.com/sivaprakashDesingu/react-voice-recorder/pull/34) Thank you for information.

**Comment by sivaprakashDesingu** [comment]
@OzdemirEmrah  Thanks for the update.

**Comment by sivaprakashDesingu** [comment]
@rohitmyaim  we resolved your issue.
