### ISSUE TITLE
Start Event callback

### ISSUE THREAD

**Issue by bhavanareddy30** [sivaprakashDesingu/react-voice-recorder#4]
Can someone please let me know how to get the startRecording callback? Right now, we only have options for AudioStop...

**Comment by sivaprakashDesingu** [comment]
Hey, There are controls button bellow of time duration, there you can see **stop, pause** icon initially, once you have paused the audio recording you can see **play icon** instead of pause icon. By clicking play icon  you can startRecording call back... have a good day!!!!

**Comment by sivaprakashDesingu** [comment]
@bhavanareddy30 I am closing this bug now, still if you find difficulties on the same, please let me know.
