### ISSUE TITLE
Failure when running Record and pressing clear

### ISSUE THREAD

**Issue by Brendan-Lucas** [sivaprakashDesingu/react-voice-recorder#5]
Steps to reproduce:

press record, press clear, press record. 

Error failed to start recording. 

I have a fix ready that I have implemented locally. If you will allow me to contribute I will submit a pull request.

**Comment by sivaprakashDesingu** [comment]
Hey Brenda,

Thanks for the fix, You can raise PR and I will check merge it with master branch.

**Comment by sivaprakashDesingu** [comment]
Fixed this on **@2.0.2** Version.
