### ISSUE TITLE
Issue with NextJS Unexpected character '�' 

### ISSUE THREAD

**Issue by JonhnyDev** [sivaprakashDesingu/react-voice-recorder#7]
Hello i have a issue with nextJS+React
./node_modules/react-voice-recorder/dist/microphone~pFtSEjGu.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by sivaprakashDesingu** [comment]
@JonhnyDev  Could you please install the latest version and try again. We have fixed in the latest version now.

Sorry for the inconvenience :)

**Comment by gradywoodruff** [comment]
Hi, i am seeing a similar error in v2.0.7 
```
ERROR in ./node_modules/react-voice-recorder/dist/stop~lbXSmHgG.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/react-voice-recorder/dist/index.modern.js 19:0-30
```
